apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server for testing
    # Use this issuer for testing to avoid rate limits
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # Email address for ACME registration
    # IMPORTANT: Replace with your actual email address
    email: admin@example.com
    
    # Name of the secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
      selector: {}
