apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    # Use this issuer for production certificates
    # Note: Subject to rate limits (50 certificates per registered domain per week)
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # Email address for ACME registration
    # IMPORTANT: Replace with your actual email address
    email: admin@example.com
    
    # Name of the secret to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: istio
      selector: {}
