apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: greenfield
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: internal
    - port: 9093
      name: external
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-lb
  namespace: greenfield
  labels:
    app: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
      name: internal
  selector:
    app: kafka
