apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cluster-slo-rules
  namespace: greenfield
  labels:
    app: prometheus
    component: slo-rules
data:
  cluster-slos.yml: |
    groups:
      - name: cluster_slos
        interval: 30s
        rules:
          # API Server Availability SLO
          # Target: 99.9% availability
          - record: apiserver:availability:ratio_rate5m
            expr: |
              sum(rate(apiserver_request_total{code!~"5.."}[5m]))
              /
              sum(rate(apiserver_request_total[5m]))
          
          - record: apiserver:availability:ratio_rate30m
            expr: |
              sum(rate(apiserver_request_total{code!~"5.."}[30m]))
              /
              sum(rate(apiserver_request_total[30m]))
          
          # Node Health SLO
          # Target: 99% nodes ready
          - record: node:health:ratio
            expr: |
              sum(kube_node_status_condition{condition="Ready",status="true"})
              /
              sum(kube_node_status_condition{condition="Ready"})
          
          # Pod Scheduling Success Rate SLO
          # Target: 99% pods successfully scheduled
          - record: pod:scheduling:success_ratio_rate5m
            expr: |
              sum(rate(kube_pod_status_scheduled{condition="true"}[5m]))
              /
              sum(rate(kube_pod_status_scheduled[5m]))
          
          # Cluster Resource Utilization - CPU
          - record: cluster:cpu:utilization
            expr: |
              sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) 
              / 
              sum(machine_cpu_cores)
          
          # Cluster Resource Utilization - Memory
          - record: cluster:memory:utilization
            expr: |
              sum(container_memory_working_set_bytes{container!=""}) 
              / 
              sum(machine_memory_bytes)
          
          # Cluster Resource Utilization - Disk
          - record: cluster:disk:utilization
            expr: |
              sum(kubelet_volume_stats_used_bytes)
              /
              sum(kubelet_volume_stats_capacity_bytes)
          
          # PVC Usage
          - record: persistentvolumeclaim:usage:ratio
            expr: |
              kubelet_volume_stats_used_bytes
              /
              kubelet_volume_stats_capacity_bytes
