# Keycloak Secret Templates
# These are placeholders - actual secrets should be created using external-secrets or sealed-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  namespace: greenfield
  labels:
    app: keycloak
type: Opaque
stringData:
  password: "REPLACE_WITH_ADMIN_PASSWORD"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: greenfield
  labels:
    app: keycloak
type: Opaque
stringData:
  username: "keycloak"
  password: "REPLACE_WITH_DB_PASSWORD"
